---
web_host: bot.gempir.com
cookie_domain: gempir.com
api_host: bot-api.gempir.com
yjs_host: bot-yjs.gempir.com
tldraw_host: bot-tldraw.gempir.com
grafana_host: grafana.o.gempir.com
prometheus_host: prometheus.o.gempir.com

postgresql_databases:
  - name: gempbot
postgresql_users:
  - name: gempbot
    password: "{{ gempbotPostgresPassword }}"

prometheus_global:
  scrape_interval: 15s

prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  - job_name: "node"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "localhost:9100"
  - job_name: "caddy"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "localhost:2019"
  - job_name: "postgres"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "localhost:9187"

prometheus_postgres_dbname: gempbot

node_exporter_arch: arm64

caddy_config: "{{ lookup('template', 'templates/Caddyfile.j2') }}"

