---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install apt packages
  apt:
    name:
      - apt-transport-https
      - ufw
      - htop
      - ncdu
      - nodejs
      - software-properties-common
    state: present

- name: Ignore default ssh in UFW
  ufw:
    rule: deny
    port: "22"
    proto: tcp

- name: Allow ssh in UFW
  ufw:
    rule: allow
    port: "32022"
    proto: tcp

- name: Allow http in UFW
  ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Allow https in UFW
  ufw:
    rule: allow
    port: "443"
    proto: tcp

- name: sshd configuration file update
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    validate: "/usr/sbin/sshd -T -f %s"
  notify:
    - restart sshd

- name: Set firewall default policy
  ufw:
    state: enabled
    policy: reject

- name: Install logrotate config
  template:
    src: templates/logrotate.j2
    dest: /etc/logrotate.d/rsyslog

- name: Install security limits
  template:
    src: templates/limits.conf.j2
    dest: /etc/security/limits.conf

- name: Ensure group "gempbot" exists
  group:
    name: gempbot
    state: present

- name: add ubuntu to gempbot group
  user:
    name: ubuntu
    groups:
      - sudo
      - gempbot
    append: yes
