- apt_key:
    url: "https://apt.grafana.com/gpg.key"
    state: present

- name: Add Repository
  apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: "present"

- name: Install
  apt:
    name: grafana
    state: present